### ISSUE TITLE
Choix des termes pour le glossaire

### ISSUE THREAD

**Issue by emchateau** [museonum/msl6517#1]
Renseignez ici vos choix pour les termes du glossaire

**Comment by smostafaei** [comment]
voici les termes du glossaire que j'ai choisi.
API (Application Programming Interface)
Dublin Core
Dictionnaires de données du RCIP
Samaneh Mostafaei

**Comment by emchateau** [comment]
Pourriez-vous, s’il vous plaît, renseigner votre nom directement dans le fichier https://github.com/museonum/MSL6517/blob/master/glossaire.md  et vous assurer que personne n’a déjà choisi vos termes.
