### ISSUE TITLE
Partager les documents de travail du groupe Ontologie

### ISSUE THREAD

**Issue by emchateau** [museonum/msl6517#20]
@BrogardMaelle a partagé avec moi le lien du Google drive du groupe @museonum/ontologie (je vous en remercie) https://drive.google.com/drive/folders/0Bw82eXC88OM5T3VOeF81UXFOY0U?usp=sharing

Il me semble qu’il s’agit de documents MSWord chargés sur Google Drive. Pour faciliter la collaboration sur les documents, il convient de les ouvrir avec Google Doc et de travailler sur ces nouveaux documents.

**Comment by ifrancon** [comment]
Bonjour,
Ne vous inquiétez pas, c'était déjà prévu. Les documents seront ouverts avec Google Docs au besoin.
Merci et bonne journée.
