### ISSUE TITLE
La question du sens des termes

### ISSUE THREAD

**Issue by vmichaud04** [museonum/msl6517#21]
@museonum/vocabulaires 

En faisant des recherches pour mon TD je suis tombée sur une citation qui pourrait nous aider à expliquer le défis de choisir les bon termes dans un vocabulaire contrôlé. Je crois que ça serait probablement le plus utile pour  Teodora, mais je la partage à tous quand même.

> To understand what it means to represent knowledge in the museum, we need the humility to appreciate that our knowledge of the world is socially constructed. Museums strive to represent what they know, but what they know was conveyed to them by someone who first made or discovered the object, collected or analysed it, or acquired it for the museum or managed it in the collection. When we say what something «is», it cannot be sad to be «true» though it may be preferable for particular purposes or «correct» from a specific perspective.

MARTY, Paul F., et Katherine BURTON JONES. Museum Informatics: People, Information, and Technology in Museums. Routledge Studies in Library and Information Science ; 2. New York: Routledge, 2008, p. 36.

Je crois que ça démontre parfaitement le fait que même si on recherche la traduction ou le terme parfait on ne le trouvera jamais, mais que c'est le prix à payer pour avoir une information organisée et accessible.

**Comment by TeodoraDim** [comment]
Merci Vanessa, en effet c’est très utile pour ma partie. Je suis d’accord que par fois la traduction ne réussit pas nécessairement à transmettre la signification, alors je parlerai plutôt d’une équivalence de terme.
