### ISSUE TITLE
Note d'intention

### ISSUE THREAD

**Issue by vmichaud04** [museonum/msl6517#22]
@museonum/ontologie 

Bonjour team ontologie!

Je viens de déposer un petit bout de texte dans le drive de groupe. C'est un début pour la partie vocabulaire de la note d'intention. Je suis la responsable de cette partie du travail pour mon équipe alors je me demandais si quelqu'un de votre équipe avait été délégué pour la note d'intention aussi? Il faudrait se rencontrer et discuter pour pondre notre beau texte. N'hésitez pas à me contacter.

Bonne journée!

Vanessa

**Comment by ifrancon** [comment]
Salut Vanessa,
Personne n'a été délégué pour le moment. Je pense que notre partie ontologie, pour la note d'intention, se fera plus ou moins en équipe (chaque sous-équipe mettant ses points importants). 
On délèguera quelqu'un (peut-être notre secrétaire) pour rendre ça cohérent avec toi. 
Je te tiens au courant.
Bonne journée !
Iloé

**Comment by vmichaud04** [comment]
Salut Iloé, 

Effectivement on peut faire des petite parties d'équipe comme j'ai fait. Cependant, Monsieur Château demande une note qui touche plus généralement au LOD en contexte culturel. Je ne crois pas que ce serait approprié qu'une seule personne se tape cette partie dans un tel travail d'équipe. Personnellement je pourrais le faire, mais je suis certaine de ne pas avoir tout compris et je pense que plus d'un cerveau serait mieux pour cette partie. Du moins pour le brainstrom et la mise en place des idées.

Qu'est-ce que tu en penses?

Vanessa

**Comment by ifrancon** [comment]
Vanessa, on est en train de s'y mettre, et dès qu'on aura un truc potable on mettra tout ensemble avec ce que tu as écrit dans le doc commun. On pourra chatter sur Drive ou Facebook si tu travailles dessus aujourd'hui :)

**Comment by OClermont** [comment]
Ok les gens @museonum/vocabulaires , on a rédigé une note d'intention! Vous pouvez y avoir accès ici : https://docs.google.com/document/d/1HPqEzgQpTknVOEwwAz2DRJj2RY7Zjq65cMdYPDrsKiQ/edit?usp=sharing
Il y a une partie surlignée en jaune dans la première page où il serait pertinent que vous rajoutiez une définition de "vocabulaire contrôlé". Vos commentaires sont les bienvenus, évidemment!

**Comment by vmichaud04** [comment]
Allô groupe ontologie, 

Vraiment désolée du délais. Je n'ai pas pu me mettre à ce projet plus tôt. Je m'assure de retravailler la note d'intention pour que tout soit parfait d'ici demain soir. 

Merci pour votre beau travail!

**Comment by emchateau** [comment]
Bonjour,
Je vous ai fait plusieurs commentaires sur la note d’intention liée ci-dessus.
Il me semble que vous devez clarifier le propos. Les données ne sont pas des choses abstraites, elles décrivent les objets conservés dans la collection. Il faut mieux mettre en évidence pourquoi il peut être intéressant de partager cette information muséale en vous demandant non seulement ce que cela peut apporter à l’institution mais aussi aux utilisateurs (chercheurs, grand public, réemplois possibles, constructions de services, etc.)

**Comment by vmichaud04** [comment]
@museonum/ontologie 
@museonum/vocabulaires 

Bonjour à tous,

Bon je travail à la reformulation de la note d'intention depuis ce matin mais comme je suis incapable de travailler sur google drive sans tout faire foirer vous ne voyez pas les modifications en live. Je vais tenter d'appliquer les correction de M. Château et publier une nouvelle version dans la nuit. 

Si vous avez des suggestions vous pouvez le faire dans le document drive. je vais y retourner souvent.

**Comment by emchateau** [comment]
Au besoin, je peux prévoir une repasse samedi soir.

**Comment by ialgrin** [comment]
C'est comme vous le souhaitez.
Nous avons prévu dans l'équipe vocabulaire que nous fassions les
remaniements (coupure, reformulation, etc) grâce aux commentaires des
membres de l'équipe à partir de samedi soir. Vos commentaires nous serons
très utiles à ce moment-là également.
Puis dimanche nous procédons aux derniers remaniements et à la mise en
commun avec l'équipe ontologie, la mise en page, etc.


2016-12-16 20:02 GMT-05:00 Emmanuel Château-Dutier <notifications@github.com

**Comment by ifrancon** [comment]
Merci !
Si on a des corrections on te fait signe Vanessa !

**Comment by vmichaud04** [comment]
Voilou!! J'ai mis un nouveau document dans votre drive de groupe qui s'appel notice d'intention version 2. J'espère que ce sera à la hauteur de vos attentes. Je crois juste qu'il manquera peut -être un petit paragraphe à la fin pour lier avec la note méthodologique. Aussi, la mise en page est mauvaise mais j'ai une version plus clean en format word si besoin est.

https://docs.google.com/document/d/1L_nuwc6mNZL7ZxdfsxFL5c4DldqdvLc7gqjzzd-n06s/edit 

Bonne nuit tout le monde!
