### ISSUE TITLE
Note d'intention LOD

### ISSUE THREAD

**Issue by OClermont** [museonum/msl6517#23]
L'équipe @museonum/ontologie se demandait s'il était possible de reprendre le texte d'une définition de glossaire d'un de nos membres pour l'inclure dans la note d'intention. Il s'agit du terme LOD, définit par @BrogardMaelle. Nous ajouterions bien sûr des informations supplémentaires à la définition.
@emchateau

**Comment by emchateau** [comment]
Pour moi aucun problème, si @BrogardMaelle est d’accord bien entendu.
