### ISSUE TITLE
Commentaires sur les documents de travail

### ISSUE THREAD

**Issue by ifrancon** [museonum/msl6517#24]
Bonsoir M. Château @emchateau ,

Si vous mettez des commentaires sur nos travaux, pourrez-vous nous indiquer sur quels documents en particulier à l'aide cette issue ? Ça nous permettra de cibler directement ces documents.

Merci !

Iloé

**Comment by emchateau** [comment]
entendu

**Comment by emchateau** [comment]
Je viens de faire des commentaires sur la note d’intention.
Pouvez-vous, s’il vous plaît, me communiquer les liens des autres documents sur lesquels vous souhaitez que je fasse des commentaires ?
Cordialement,
Emmanuel Château

**Comment by emchateau** [comment]
J'avais initialement proposé de travailler sur ce document https://docs.google.com/document/d/1-Pso7g35pymRbats9ValMkURbwGqFUTU8BFftyO94xw/edit?usp=sharing

**Comment by emchateau** [comment]
pour le groupe ontologie, vos textes sont visiblement dans le répertoire "rédaction travail final" https://drive.google.com/drive/folders/0Bw82eXC88OM5RmVQa09VTHlMZ28

et "préparation des documents à rendre" pour le groupe vocabulaire https://drive.google.com/drive/folders/0B5Vma2_CDMPlX01ZZHhrcmZBU28

Je vais les consulter dans la soirée.

**Comment by ialgrin** [comment]
Bonsoir,
nos documents, concernant l'équipe de travail sur les vocabulaires, sont au
stade de brouillon. L'équipe ajoute actuellement ses commentaires jusqu'à
samedi en fin d'après-midi, afin que je puisse effectuer la formulation et
la mise en commun avec l'équipe ontologie samedi soir et dimanche.
Vos commentaires pourrons donc nous être utiles pour effectuer la
reformulation.
Aussi, le scénario n'est pas encore rédigé.
Vous trouverez les documents dans le dossier "Préparation des documents à
rendre".
En espérant que ce message vous sera utile.

2016-12-16 19:17 GMT-05:00 Emmanuel Château-Dutier <notifications@github.com

**Comment by emchateau** [comment]
J’ai bien conscience qu’il s’agit de brouillons. Je peux prévoir une relecture des deux groupes samedi dans la soirée si vous voulez.

**Comment by ifrancon** [comment]
Pour faire suite au message d'Isabelle, dans notre cas, les parties terminées sont identifiées par la mention "TERMINÉE".
Bonne soirée.

**Comment by emchateau** [comment]
@museonum/etudiants2016 

Bonsoir, 
Je viens de faire une relecture des documents mis en ligne et j'ai ajouté quelques commentaires et corrections. Généralement votre travail avance dans la bonne direction. Le propos devient relativement limpide et on sent bien que vous commencez à bien vous approprier le domaine.

Veillez bien à justifier le plus possible vos choix et vos appréciations. N’hésitez pas préciser et détailler vos raisonnements. 

N’oubliez pas non plus que vous pouvez rédiger des passages sous la forme de listes ou d’encadrés pour indiquer les écueils possibles de telle ou telle approche, signaler des points de vigilance, fournir un résumé opérationnel, etc. Mais aussi insérer des figures et des illustrations qui vous serviront aussi aux présentations.

Bon courage. Si vous le souhaitez, je peux encore faire une relecture des contenus demain dans la journée.

Emmanuel Château

**Comment by ifrancon** [comment]
@emchateau 
Bonjour M. Château,
Comme nous avons d'autres travaux à finaliser pour demain, nous avons commencé la mise en page finale de ce travail. Nous n'aurons pas le temps de prendre en compte tout commentaire supplémentaire (si ça peut vous éviter de perdre du temps). 
Merci !
Iloé

**Comment by ialgrin** [comment]
Bonjour, je confirme le message d'Iloé, nous sommes en pleine mise en page et nous n'aurons pas de temps pour les modifications éventuelles, étant donné les autres travaux à rendre.
Nous vous remercions toutefois pour votre propositions et pour les commentaires apportés hier soir, nous en avons tenu compte au maximum.
En vous souhaitant une bonne fin de semaine
