### ISSUE TITLE
évaluation des paires 

### ISSUE THREAD

**Issue by annalougalassini** [museonum/msl6517#25]
Bonjour, @emchateau 

Pouvez-vous nous expliquer comment devrons nous procéder pour l'évaluation de nos coéquipiers. Voulez vous que l'on vous fournisse un document rédigé ou bien aviez-vous penser à une grille que vous fournirez  ? 
Cordialement,

Anna-lou Galassini

**Comment by emchateau** [comment]
Je vous expliquerai cela lundi.
Merci
