### ISSUE TITLE
Évaluation des pairs 

### ISSUE THREAD

**Issue by OClermont** [museonum/msl6517#28]
Bonjour @emchateau ,
Est-ce que nous aurons accès au document pour l’évaluation des pairs aujourd'hui, question de respecter la date butoir pour les évaluations qui est fixée au 23 décembre?
Merci.

**Comment by emchateau** [comment]
Bonjour,
Cette date concerne, à ma connaissance, les examens, pas les évaluations. Je vous mets le formulaire en ligne avant la fin de la semaine.
Mes notes seront rendues début janvier.
Cordialement,
Emmanuel
