### ISSUE TITLE
Vocabulaire discussion

### ISSUE THREAD

**Issue by vmichaud04** [museonum/msl6517#9]
@museonum/vocabulaires 

Bonjour à tous! Voici un résumé de ce qui a été discuté ce matin en réunion.

Nos intentions pour la partie vocabulaire (à compléter plus tard):

- Faire une recherche sur les vocabulaires disponibles, surtout en anthropologie et pour les noms de lieux (en anglais et en français)
- Comparer avec les vocabulaires et thésaurus déjà utilisés par Violaine (SMQ et vocabulaire maison) et voir si un mapping/correspondance est possible.
- Évaluer si des vocabulaires en langues autochtones existent, seraient vraiment utiles ou carrément non fonctionnels.
- Exposer nos suggestions à la suite de ces recherches.

Tâches à accomplir d'ici lundi le 14 novembre:

- Tous se familiariser avec les enjeux, perspectives d'avenir, etc. que représentent les données liées pour les musées et les collections anthropologiques.
- Former notre propre opinion sur ces différent points et formuler toute questions pouvant s'adresser à Monsieur Château.

Tâches à accomplir dans un futur proche : 

- Laurie: chercher sur le web des vocabulaires en langues autochtones et voir s'ils pourraient vraiment être fonctionnels pour le projet.
- Jean-Michel: Voir avec quels vocabulaires ou ressources on pourrait standardiser les noms de lieux.
- Thibaut: Contacter des institutions conservant des collections culturelles autochtones pour comprendre comment elles gèrent les difficultés reliés aux langues autochtones.
- Teodora: Faire quelques recherches sur les vocabulaires applicables à l'anthropologie et juger lesquels semblent les plus complets dans le domaines des objets culturels autochtones du nord du Canada. (Nomenclature 4.0/Parc Canada/Cultural Objects Name Authority/autres)
- Isabelle: Rédiger la méthodologie de notre groupe et discuter avec un représentant de l'autre groupe pour la mise en commun. 
- Vanessa: Rédiger la note d'intention en partenariat avec un représentant de l'autre groupe

Questions à poser au professeur lundi le 14 novembre:

- Avait-il déjà envisagé une stratégie pour faciliter la rédaction des parties de groupe ? Sinon proposer notre méthode de représentants.
- Est-ce que la partie méthodologie doit se faire en groupe ou chaque équipe écrit simplement sa méthodologie propre ?
- Quand peut-on s'attendre à recevoir les informations qui lui ont été transmises par Violaine sur les vocabulaires quelle utilise et la liste des objets à considérer ? (Isabelle ne communiquera pas avec Violaine tout de suite étant donné que le prof semble dire qu'il a déjà reçu l'information et que de toute façon Violaine ne répondrait pas avant lundi)
- Apporter des précisions aux dates de rendues suivantes : 28 novembre - groupe vocabulaires ET 5 décembre - groupe ontologie.
- Revenir sur la notion de SKOS et de OWL. Est-ce que ce sont des vocabulaires pour le web sémantique? Des modèles conceptuels ? Les deux ?
- Comment vérifier si des URI relatifs à des entités spécifiques existent déjà ?

SVP n'hésitez pas à ajouter quoi que ce soit que j'aurais oublié. Je propose aussi que l'on ajoute toutes nos questions à celles mentionnées ici au cours de la fin de semaine comme cela nous serons certains de demander toute l'information dont nous avons besoin dans le cours de lundi.

Finalement, notez que j'ai créé un Labels Vocabulaire. Je vais écrire tous les résumés de réunion via github alors si vous cherchez une info précise, vous pouvez trier avec ce label. J'ai fais ça car le prof semble vouloir être au courant de toutes nos discussions, chose qui ne serait pas possible sur un Drive d'équipe. Par contre, je propose que l'on utilise ce drive d'équipe pour toute rédaction avant de mettre sur le Drive de groupe. Ce sera plus facile à gérer si nous avons des commentaires, suggestions et autres que d'exposer un gros brouillon au groupe entier.

Notre drive d'équipe : https://drive.google.com/drive/folders/0B5Vma2_CDMPlSG5IRXlBcVlZSWs?usp=sharing 

Voilà! À lundi tout le monde. Et n'oublier pas notre petite rencontre «catch up» après le cours de lundi.

Vanessa

**Comment by Abasiee** [comment]
J'ai ajouter une petite question que j'avais au sujet des dates de rendues et j'ai aussi supprimer le document de questions du Drive puisqu'il sera plus simple de faire le suivi ici. 

Merci Vanessa !

**Comment by vmichaud04** [comment]
Bonjour à tous! 

Alors tel que discuté après le cours de ce matin, tout le monde se sent encore un peut perdu par rapport au projet. On continue nos recherches individuelles cette semaine et on profite du fait qu'il n'y a pas de cours lundi pour se rencontrer et avancer un peut la partie vocabulaire lundi le 21 novembre de 10h à 12h au local C-5048.

Sinon on continue à communiquer sur le drive d'équipe.

Voici un document qui aurait probablement de très bonnes ressources pour nous en bibliographie : 

http://sciencepourlepublic.ca/uploads/fr/assessments%20and%20publications%20and%20news%20releases/memory/CofCA_14-377_MemoryInstitutions_WEB_F.PDF 

Bisous! 

Vanessa

**Comment by vmichaud04** [comment]
http://canada.pch.gc.ca/fra/1443536696562

**Comment by ialgrin** [comment]
Discuté ce matin en réunion  : 
Choix des vocabulaires :
- Liste de vocabulaires existants : http://canada.pch.gc.ca/fra/1443536696562 
- Linked Open Vocabularies : https://lov.okfn.org/dataset/lov/vocabs

- Parc Canada pour anthropologie. Utiliser le dictionnaire visuel et descriptif du RCIP. Parc Canada comprend une partie de AAT, mais l’avantage est qu’il est bilingue français et anglais, mais pas en LOD. Il est basé sur des objets trouvés dans les parcs nationaux du canada et donc pertinent pour les collections amérindiennes d’objets trouvés au Canada. 
Il faudrait comparer les deux vocabulaires pour savoir lequel comprend le plus d’informations sur des collections anthropologiques. Le AAT est plus utilisé dans le LOD on est capable d’utiliser pour la majeure partie de la collection, puis il pourrait être complété avec des équivalences en français grâce au vocabulaire de Parcs Canada.
Il faudrait également voir si on peut compléter avec des dictionnaires en langues autochtones, par exemple avec ceux déjà utilisés par Violaine.

Question à poser à Emmanuel Château : 
Il faudrait savoir si il est plus facile de prendre un vocab déjà adapté et traduit dans les fiches de la collection mais pas dans LOD, ou prendre un vocabulaire pas encore utilisé dans sa collection qui demanderait de réviser les fiches de catalogage, et de traduire ou compléter les termes en français, mais qui est dans le LOD.

Ce que nous allons faire c’est prendre quelques objets chacuns dans l’échantillon puis voir quelles équivalences sont efficaces :
1-4 : Vanessa
5-8 : Théodora
9-12 : Isabelle
13-16 : Thibaut
17-20 : Jean-Michel
21-26 : Laurie


Il faut faire les comparaisons de la même manière pour les objets avec :
- toponymie : Jean-Michel
- langues autochtones : Thibaut
- matériaux : theodora
- fabrication et techniques : Laurie
- attributs : vanessa
- Mise en commun des idées et conclusions (en point form) pour 28 nov : Isabelle


N.B. : Geonames pour les noms de lieux français et anglais et on peut ajouter d’autres noms s’ils sont absents.
Dictionnaire en langue innue en ligne déjà utilisé par Violaine.
pour les matériaux et techniques de fabrication on devrait utiliser le AAT car recommandé par RCIP.
période de temps : pas de vocabulaire à fournir car les collectons sont contemporaines donc l'intervalle est peu pertinent à étudier et il n’y a pas différentes périodes à étudier.

**Comment by vmichaud04** [comment]
Salut tout le monde! 

Je viens de voir que seulement trois personne ont mis leur comparatif de vocabulaire dans le fichier que Isabelle a créé sur google drive. Rappellez-vous qu'elle doit faire une petite mise en commun de tout ca pour lundi alors s'il était possible pour ceux qui n'ont pas contribué encore de ne pas attendre trop à la dernière minute je suis certaine qu'Isabelle apprécierait. 

Aussi, nous avions chacun un autre type de vocabulaire à analyser (exemple moi c'était les vocabulaires d'attributs), mais je n'ai encore rien vu de ces recherches sur le drive. Allez up tout le monde il ne reste que trois semaines et c'est les vacances!!

Merci!!

**Comment by tbourgui** [comment]
Oups, desolé, je l'ai mercredi mais j'ai oublié de le mettre... Je fais ça de suite. =)

**Comment by ialgrin** [comment]
Hello team ! Merci pour vos contributions, je vais essayer de résumer tout ça :)
@JiMGodbout peux-tu inclure ton paragraphe sur les toponymies et me prévenir lorsque tu auras fini ? Ça m'évite de passer vérifier pour rien sur le doc :P 
Merci !

**Comment by vmichaud04** [comment]
Allô tout le monde!

Alors en premier lieux sachez que j'ai réservé le local pour nos rencontre (le même que d'habitude).  On se rencontre ce vendredi 2 décembre à 10h am. Svp confirmez que vous y serai.

La plus grosse problématique qui sera abordé lors de cette réunion sera de développer un scénario d'application pour les vocabulaires. Je ne suis pas tout à fait certaine d'avoir compris en quoi consiste le scénario, mais je crois qu'il faut choisir une problématique précise (ex : la création d'un vocabulaire spécifique pour la collection) et essayer d'expliquer concrètement comment on proposerait de le faire et les avantages de cette stratégie pour le contextes  de la collection d'ethnologie et pour Violaine.  Il existes de multiples voies pour ce scénario alors on décidera lequel on veut explorer le plus. 

On semblerait sur la bonne voie alors Jean-Michel, Théodora et moi avons pensé que nous étions peut-être rendu à l'étape de composer de réels paragraphes selon différentes thématique à explorer que nous avons discuté en classe ce matin. Je vous propose donc une liste de thématiques/paragraphes à écrire selon ce que j'ai compris. N'hésitez pas à compléter la liste selon vos idées et désirs. 

**Note méthodologique spécifique au vocabulaire** (à inclure dans nos pages et pas dans la méhodologie de groupe).

- Quels outils site web ont été consultés, pourquoi,leur structure, utilité ou pas, etc. (penser à parler de la page Vocabulaires(normes terminologiques) du RCIP et lov.okfn.org).
- Quel méthodes de comparaison et d'analyse on a utilisé
- Quels vocabulaires ont été étudiés avec cette méthode

**Vocabulaires de nomenclature des objets** (J'encourage l'utilisation d'exemple concrets dans cette partie)

- Pourquoi on a analysé ceux-là (ajouter une petite section sur le thesaurus du National Museum of the American Indian)
-Avantages de chacun (penser au fai qu'ils sont déjà traduits ou pas, en LOD ou pas, etc.)
-Désavantages de chacun ( problème de la perspective occidentale des termes, nécessité de Skosifier le vocab. du RCIP ou attendre que le RCIP le développe en LOD, vocabulaires à facettes qui partent de présupposés pas forcément conforme avec la réalité de notre collection (revient à un problème avec la structure hiérarchique des vocabulaires), etc.)

**Vocabulaire de nom de lieux**

- vocabulaires analysés
- Avantages et désavantages de chacun

Jean-Michel je te laisse le soins de compléter cette liste comme tu es beaucoup plus familier avec le sujet que 

**Autres vocabulaires** **(Vanessa)** (je propose de tous les regrouper vu que les réflexions vont pas mal être pareil de l'un à l'autre)

- Vocabulaires analysés (physical attributes, materials, techniques and processes, etc.)
- Avantages qu'ils représentent (uniformisation du cataloguage, stucture hiérarchique qui aide au moins à trouver des termes plus génériques, même si pas exact dans signfication, pause moins de problème que nomenclature parce que en cas de gros problème ces champs peuvent ne pas être renseignés car moins cruciaux que le nom d'objet, etc.)
- Désavantages (peut-être pas assez complets,etc.)

**Création d'un vocabulaire adapté**

- Avantages versus tout ce que ca implique comme temps, infrastructures, ressources financières et humaines, etc.
- Solution possibles (collaboration avec d'autres institutions)

**Problème de la langue**

- Étant au Canada, un peu obligé d'être englais/francais
- Les langues autochtones seraient un but de la responsable de la collections, mais existe pas de dictionnaire exhaustif alors obligation d'avoir recours à d'autres institutions ou des linguistes. 
-Problème de la multiplicité des groupes linguistiques et même des dialectes utilisés d'une région  à une autre, etc.
-Problème de la temporalité de faire toutes les équivalences et mettre ça en LOD.

**Scénario**

À développer en commun vendredi le 2 décembre



Je propose qu'on écrive notre nom à côté des paragraphes que nous aimerions aborder. Aussi, ne pensez pas qu'il faut avoir fait ça avant vendredi. Personnellement je sais que je ne pourrai rien avancer d'ici là, mais au moins ça nous donne une direction. Avec tout ça je pense qu'on a même une structure de texte assez cohérente pour notre section d'équipe.

M. Château  a aussi parler d'étudier plus en détail le Reciprocal Research Network. Je ne savais pas trop où l'inclure dans la liste, mais si ça vous intéresse mettez votre nom ici : 

Voilà! N’hésitez de mettre votre nom à côté des parties que vous désirer faire et lâcher vous loose sur les commentaires et autres. 

Bonne journée tout le monde!

**Comment by emchateau** [comment]
Pour le scénario, ce n’est pas forcément choisir une problématique précise, mais cela consiste plutôt en un cas d’usage qui permette d’exemplifier l’intérêt du travail sur les vocabulaires et le parti que pourrait en tirer la collection.

**Comment by ialgrin** [comment]
Merci pour le résumé Vanessa :)  Je confirme que je serai présente pour la rencontre vendredi !
Je me suis notée, *étonnement général* pour la note méthodologique, mais si quelqu'un voulait la faire, j'ai aucun souci avec les autres parties, donc manifestez-vous :)

**Comment by tbourgui** [comment]
Salut! 

Je confirme ma présence pour vendredi 10h! 

Thibaut 

----- Mail original -----

De: "vmichaud04" <notifications@github.com> 
À: "museonum/msl6517" <msl6517@noreply.github.com> 
Cc: "tbourgui" <thibaut-bourguignon@laposte.net>, "Team mention" <team_mention@noreply.github.com> 
Envoyé: Lundi 28 Novembre 2016 14:12:05 
Objet: Re: [museonum/msl6517] Vocabulaire discussion (#9) 



Allô tout le monde! 

Alors en premier lieux sachez que j'ai réservé le local pour nos rencontre (le même que d'habitude). On se rencontre ce vendredi 2 décembre à 10h am. Svp confirmez que vous y serai. 

La plus grosse problématique qui sera abordé lors de cette réunion sera de développer un scénario d'application pour les vocabulaires. Je ne suis pas tout à fait certaine d'avoir compris en quoi consiste le scénario, mais je crois qu'il faut choisir une problématique précise (ex : la création d'un vocabulaire spécifique pour la collection) et essayer d'expliquer concrètement comment on proposerait de le faire et les avantages de cette stratégie pour le contextes de la collection d'ethnologie et pour Violaine. Il existes de multiples voies pour ce scénario alors on décidera lequel on veut explorer le plus. 

On semblerait sur la bonne voie alors Jean-Michel, Théodora et moi avons pensé que nous étions peut-être rendu à l'étape de composer de réels paragraphes selon différentes thématique à explorer que nous avons discuté en classe ce matin. Je vous propose donc une liste de thématiques/paragraphes à écrire selon ce que j'ai compris. N'hésitez pas à compléter la liste selon vos idées et désirs. 

Note méthodologique spécifique au vocabulaire (à inclure dans nos pages et pas dans la méhodologie de groupe). 

    * Quels outils site web ont été consultés, pourquoi,leur structure, utilité ou pas, etc. (penser à parler de la page Vocabulaires(normes terminologiques) du RCIP et lov.okfn.org). 
    * Quel méthodes de comparaison et d'analyse on a utilisé 
    * Quels vocabulaires ont été étudiés avec cette méthode 


Vocabulaires de nomenclature des objets (J'encourage l'utilisation d'exemple concrets dans cette partie) 

    * Pourquoi on a analysé ceux-là (ajouter une petite section sur le thesaurus du National Museum of the American Indian) -Avantages de chacun (penser au fai qu'ils sont déjà traduits ou pas, en LOD ou pas, etc.) -Désavantages de chacun ( problème de la perspective occidentale des termes, nécessité de Skosifier le vocab. du RCIP ou attendre que le RCIP le développe en LOD, vocabulaires à facettes qui partent de présupposés pas forcément conforme avec la réalité de notre collection (revient à un problème avec la structure hiérarchique des vocabulaires), etc.) 


Vocabulaire de nom de lieux 

    * vocabulaires analysés 
    * Avantages et désavantages de chacun 


Jean-Michel je te laisse le soins de compléter cette liste comme tu es beaucoup plus familier avec le sujet que 

Autres vocabulaires (Vanessa) (je propose de tous les regrouper vu que les réflexions vont pas mal être pareil de l'un à l'autre) 

    * Vocabulaires analysés (physical attributes, materials, techniques and processes, etc.) 
    * Avantages qu'ils représentent (uniformisation du cataloguage, stucture hiérarchique qui aide au moins à trouver des termes plus génériques, même si pas exact dans signfication, pause moins de problème que nomenclature parce que en cas de gros problème ces champs peuvent ne pas être renseignés car moins cruciaux que le nom d'objet, etc.) 
    * Désavantages (peut-être pas assez complets,etc.) 


Création d'un vocabulaire adapté 

    * Avantages versus tout ce que ca implique comme temps, infrastructures, ressources financières et humaines, etc. 
    * Solution possibles (collaboration avec d'autres institutions) 


Problème de la langue 

    * Étant au Canada, un peu obligé d'être englais/francais 
    * Les langues autochtones seraient un but de la responsable de la collections, mais existe pas de dictionnaire exhaustif alors obligation d'avoir recours à d'autres institutions ou des linguistes. -Problème de la multiplicité des groupes linguistiques et même des dialectes utilisés d'une région à une autre, etc. -Problème de la temporalité de faire toutes les équivalences et mettre ça en LOD. 


Scénario 

À développer en commun vendredi le 2 décembre 

Je propose qu'on écrive notre nom à côté des paragraphes que nous aimerions aborder. Aussi, ne pensez pas qu'il faut avoir fait ça avant vendredi. Personnellement je sais que je ne pourrai rien avancer d'ici là, mais au moins ça nous donne une direction. Avec tout ça je pense qu'on a même une structure de texte assez cohérente pour notre section d'équipe. 

M. Château a aussi parler d'étudier plus en détail le Reciprocal Research Network. Je ne savais pas trop où l'inclure dans la liste, mais si ça vous intéresse mettez votre nom ici : 

Voilà! N’hésitez de mettre votre nom à côté des parties que vous désirer faire et lâcher vous loose sur les commentaires et autres. 

Bonne journée tout le monde!

**Comment by JiMGodbout** [comment]
Moi aussi

Le 2016-11-30 à 09:45 AM, "tbourgui" <notifications@github.com<mailto:notifications@github.com>> a écrit :


Salut!

Je confirme ma présence pour vendredi 10h!

Thibaut

----- Mail original -----

De: "vmichaud04" <notifications@github.com<mailto:notifications@github.com>>
À: "museonum/msl6517" <msl6517@noreply.github.com<mailto:msl6517@noreply.github.com>>
Cc: "tbourgui" <thibaut-bourguignon@laposte.net<mailto:thibaut-bourguignon@laposte.net>>, "Team mention" <team_mention@noreply.github.com<mailto:team_mention@noreply.github.com>>
Envoyé: Lundi 28 Novembre 2016 14:12:05
Objet: Re: [museonum/msl6517] Vocabulaire discussion (#9)



Allô tout le monde!

Alors en premier lieux sachez que j'ai réservé le local pour nos rencontre (le même que d'habitude). On se rencontre ce vendredi 2 décembre à 10h am. Svp confirmez que vous y serai.

La plus grosse problématique qui sera abordé lors de cette réunion sera de développer un scénario d'application pour les vocabulaires. Je ne suis pas tout à fait certaine d'avoir compris en quoi consiste le scénario, mais je crois qu'il faut choisir une problématique précise (ex : la création d'un vocabulaire spécifique pour la collection) et essayer d'expliquer concrètement comment on proposerait de le faire et les avantages de cette stratégie pour le contextes de la collection d'ethnologie et pour Violaine. Il existes de multiples voies pour ce scénario alors on décidera lequel on veut explorer le plus.

On semblerait sur la bonne voie alors Jean-Michel, Théodora et moi avons pensé que nous étions peut-être rendu à l'étape de composer de réels paragraphes selon différentes thématique à explorer que nous avons discuté en classe ce matin. Je vous propose donc une liste de thématiques/paragraphes à écrire selon ce que j'ai compris. N'hésitez pas à compléter la liste selon vos idées et désirs.

Note méthodologique spécifique au vocabulaire (à inclure dans nos pages et pas dans la méhodologie de groupe).

* Quels outils site web ont été consultés, pourquoi,leur structure, utilité ou pas, etc. (penser à parler de la page Vocabulaires(normes terminologiques) du RCIP et lov.okfn.org<http://lov.okfn.org>).
* Quel méthodes de comparaison et d'analyse on a utilisé
* Quels vocabulaires ont été étudiés avec cette méthode


Vocabulaires de nomenclature des objets (J'encourage l'utilisation d'exemple concrets dans cette partie)

* Pourquoi on a analysé ceux-là (ajouter une petite section sur le thesaurus du National Museum of the American Indian) -Avantages de chacun (penser au fai qu'ils sont déjà traduits ou pas, en LOD ou pas, etc.) -Désavantages de chacun ( problème de la perspective occidentale des termes, nécessité de Skosifier le vocab. du RCIP ou attendre que le RCIP le développe en LOD, vocabulaires à facettes qui partent de présupposés pas forcément conforme avec la réalité de notre collection (revient à un problème avec la structure hiérarchique des vocabulaires), etc.)


Vocabulaire de nom de lieux

* vocabulaires analysés
* Avantages et désavantages de chacun


Jean-Michel je te laisse le soins de compléter cette liste comme tu es beaucoup plus familier avec le sujet que

Autres vocabulaires (Vanessa) (je propose de tous les regrouper vu que les réflexions vont pas mal être pareil de l'un à l'autre)

* Vocabulaires analysés (physical attributes, materials, techniques and processes, etc.)
* Avantages qu'ils représentent (uniformisation du cataloguage, stucture hiérarchique qui aide au moins à trouver des termes plus génériques, même si pas exact dans signfication, pause moins de problème que nomenclature parce que en cas de gros problème ces champs peuvent ne pas être renseignés car moins cruciaux que le nom d'objet, etc.)
* Désavantages (peut-être pas assez complets,etc.)


Création d'un vocabulaire adapté

* Avantages versus tout ce que ca implique comme temps, infrastructures, ressources financières et humaines, etc.
* Solution possibles (collaboration avec d'autres institutions)


Problème de la langue

* Étant au Canada, un peu obligé d'être englais/francais
* Les langues autochtones seraient un but de la responsable de la collections, mais existe pas de dictionnaire exhaustif alors obligation d'avoir recours à d'autres institutions ou des linguistes. -Problème de la multiplicité des groupes linguistiques et même des dialectes utilisés d'une région à une autre, etc. -Problème de la temporalité de faire toutes les équivalences et mettre ça en LOD.


Scénario

À développer en commun vendredi le 2 décembre

Je propose qu'on écrive notre nom à côté des paragraphes que nous aimerions aborder. Aussi, ne pensez pas qu'il faut avoir fait ça avant vendredi. Personnellement je sais que je ne pourrai rien avancer d'ici là, mais au moins ça nous donne une direction. Avec tout ça je pense qu'on a même une structure de texte assez cohérente pour notre section d'équipe.

M. Château a aussi parler d'étudier plus en détail le Reciprocal Research Network. Je ne savais pas trop où l'inclure dans la liste, mais si ça vous intéresse mettez votre nom ici :

Voilà! N'hésitez de mettre votre nom à côté des parties que vous désirer faire et lâcher vous loose sur les commentaires et autres.

Bonne journée tout le monde!

-
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub , or mute the thread .


-

**Comment by Abasiee** [comment]
Je confirme ma présence, j’espérais être là physiquement cette fois mais pas moyen .. je vous accompagnerais donc via Hangout :)

**Comment by vmichaud04** [comment]
Bonjour à tous,

Voili voilou un petit résumé de ce matin.

Alors tout le monde c'est vu attribué une partie du travail à faire ce matin. On ne s'attend pas à avoir un produit fini lundi mais plutôt un premier jet écrit en vrai texte pour vendredi le 9. Isabelle essayera de mettre ça plus ou moins en commun pour lundi le 12. 

On attend à lundi des précisions/exemples de scénario pour se lancer dans cette partie du travail étant donné que tout le monde semble avoir compris des trucs un peu différents. 

Aussi, j'ai pensé à une petite stratégie en retournant chez moi. J'ai pensé qu'on pourrait faire des équipes de deux pour travailler sur certaines parties plus difficiles du travail. 

Par exemple, je pense que Théodora aura une grosse partie du travail à faire avec les vocabulaires de nomenclatures alors j'ai pensé que ça pourrait être isabelle qui l'aide à compléter vu que sa partie est très liée. 

Aussi, Laurie aura une grosse tâche à faire vu que nous n'avons pas encore exploré trop trop ça implique quoi de faire un nouveau vocabulaire et que la skosification c'est un peu abstrait, j'ai pensé que Thibaut ou J-M pourraient l'aider avec la recherche de cette partie là alors que l'autre m'aiderait à faire la recherche pour contextualiser les vocabulaires dans le LOD (Genre répondre aux questions posées pas M. Château). 

Je pense qu'avec cette stratégie ça nous permettra de moins se perdre dans les recherches et d'être un peu plus structuré. 

Laissez moi savoir ce que vous en pensez. 

Bon weekend!

Vanessa

**Comment by ialgrin** [comment]
Idées de scénarios (vu en cours du 5 décembre):


Développement d’un microthésaurus sur la désignation des objets culturels autochtones
pourquoi c’est intéressant de le faire  du point de vue des enjeux terminologiques
parler des différents vocabulaires existants.
deux zones à représenter dans la collection : zone subarctique et arctique
voir comment faire pour l’interopérabilité avec le vocabulaire du Getty
identifier les ressources auxquelles on a accès
quels sont les enjeux pour la création de ce vocabulaire
quel apport du point de vue technologique
ambiguïtés vocabulaires, multilinguisme
formuler l’idée que le projet devrait envisager de contacter les institutions similaires et envisager un travail en réseau entre ces institutions pour permettre la mise en commun des informations et de la documentation, produire un vocabulaire commun et le diffuser en groupe pour avoir plus de poids pour en faire la proposition auprès d’autorités telles que le Getty si on souhaite le proposer pour perfectionner une de leurs part de vocabulaire. 
quel format utiliser pour la publication de vocabulaires ? SKOS
Comment on le fait ??
envisager le mapping : quelles possibilités ? qu’utiliser ? google refine, karma, etc.


Microthésaurus : Subdivision d'un thésaurus correspondant à un regroupement de termes autour d'un même thème ou champ sémantique. L'ensemble des microthésaurus constitue le thésaurus.
Source : http://www.adbs.fr/microthesaurus-17837.htm?RH=OUTILS_VOC


Proposition suite à discussion de groupe en fin de cours :
Comme prévu, chacun travaille la partie qu’il a choisi lors d ela réunion précédente.
Envoi de ce qui a pu être rédigé le vendredi 9 au soir pour qu’Isabelle puisse travailler la note méthodologique le weekend.
Isabelle pourrait aider Thibaut à travailler sur les vocabulaires et la question de la linguistique, puis travailler à la mise à l’écrit du scénario à partir des notes ci-dessus.

**Comment by vmichaud04** [comment]
Merci isabelle pour le résumé! 

Si je peux me permettre, j'aimerais apporter une petite précision sur ce que moi j'ai compris de comment ça pourrait s’articuler. 

En fait, je m'imagine que beaucoup des points que tu as mentionné peuvent entrer dans la partie à Laurie car c'est elle qui s'occupe de la question de créer un thésaurus adapté aux besoins spécifiques de la collection (en touchant la question des langue mais juste l'anglais et le français peut-être). 

Pour sa part, Thibaut pourrait faire une section juste sur les langues autochtones qui serait en fait notre scénario. Sans nécessairement revoir toute les question du mapping et de la skosification que Laurie aura déjà touché, peut être plus se concentrer sur les problématiques reliées à ces langues spécifiquement et de voir quels seraient les avantages de faire apparaître les langues autochtones dans le lod (pour l'université comme pour les usagers) et comment ça pourrait se faire (collaboration avec des linguistes et autres institutions spécialistes, etc.).

Voilà. C'est la façon dont j'avais vu ça pour ne pas qu'il y ait trop de répétitions entre les parties de Laurie et de Thibaut. Dites moi si c'est comme ça que vous l'aviez envisagé aussi ou laisser tout vos commentaire et suggestions si vous aviez vu ça autrement.

Bonne journée!

**Comment by ialgrin** [comment]
Oui tu as bien raison Vanessa, c'est mieux avec tes précisions :)

**Comment by ialgrin** [comment]
Pour les parties à rédiger et que je vais tenter de mettre en commun, pourriez-vous les mettre dans le dossier "Mise en commun 9 décembre" ?
On commence à avoir beaucoup de fichiers et si les choses ne sont pas bien identifiées ça devient difficile pour moi de m'y retrouver quand vient le mise en commun...
Merciiiiiiii :D

**Comment by ialgrin** [comment]
Autre remarque : il faudrait écrire vos documents directement dans le google drive ou copier coller vos textes sur des documents google pour qu'on puisse s'en servir.
Les docs word, open office etc, s'affichent comme des images à l'ouverture et à moins de retaper tout le texte, ne sont pas utilisables pour la mise en commun ;)

**Comment by JiMGodbout** [comment]
http://www.innu-aimun.ca/dictionary/Words 
Il y a déjà un dictionnaire innu-franco-anglo sur ce site ça pourrait être un bon point de départ

**Comment by ialgrin** [comment]
Les amis j'ai créé des documents qui serviront à produire les notes finales à rendre dans le cadre du cours. Elles sont bien sûr au stade de brouillon, mais chaque note comporte la liste des éléments demandés par Monsieur Château, que nous devrions suivre pour faciliter la rédaction pour nos parties vocabulaire, mais aussi pour la mise en commun avec le groupe ontologie.
Je pourrai avancer sur la note stratégique (mise en commun), la note méthodologique et le scénario au courant de la semaine.
Nous avons vraiment beaucoup de contenu et il va falloir que nous limitions nos écrits pour avoir un ensemble de notes synthétiques et pertinentes :)
Donc pas d'inquiétude si finalement les notes ne sont pas très longues, on avait imaginé un genre de 3 pages chaque et il faut penser à la mise en commun avec le groupe ontologie, avec un document final d'une vingtaine de pages.
À demain :)

**Comment by ialgrin** [comment]
Allo team ! Il faudrait que vous alliez consulter le document "**COMPARAISON DES VOCABULAIRES**" dans le dossier de préparation des documents à rendre sur notre google drive.
Pour l'instant ce ne sont que vos notes mises bout à bout dans l'ordre que nous avons discuté. Comme cela fait 10 pages, **il faudrait que chacun commente sur le document ce qui pourrait être enlevé ou ce qui est répétitif, pas utile, etc.** 
Aussi pensez a noter vos references completes dans vos documents entre parentheses, pour que je puisse faire les notes de bas de page, qui prennent beaucoup de temps.
De cette façon je pourrai faire la mise en commun plus efficacement, pour rappel j'ai aussi un travail à rendre conséquent pour lundi :p 
Il faudrait que ce soit fait pour **samedi fin d'après midi.**
Je dois faire la mise en commun de nos documents dimanche avec l'équipe ontologie.
Par ailleurs, si vous voulez contribuer à la note methodologique pour y mettre vos references de thesaurus vocabulaires consultés etc, ce serait vraiment sympa. OU y ajouter des points qui vous semblent important et que je devrais indiquer à l'écrit.
Même chose pour le scenario si vous avez des idées précises.
Merci

**Comment by ialgrin** [comment]
J'ai écrit une ébauche de ce qui pourrait être notre note méthodologique.
Merci d'y ajouter vos commentaire pour me signaler ce que j'ai oublié ou tout autre information utile :)
J'ai fait ça très court et très synthétique donc n'hésitez pas :)

**Comment by ialgrin** [comment]
Pour vous donner une idée de ce qu'on s'est dit en commun avec l'équipe ontologie, notre rapport doit avoir cette longueur approximative : 
-  3 à 5 pages communes pour note intention
- 3 à 5 pages communes pour note methodo
- 10 pages note strategique + scenario  (chaque equipe)
Donc il faut qu'on écourte et synthétise la note stratégique :)

**Comment by vmichaud04** [comment]
@Abasiee @TeodoraDim 

Salut les filles, on attend encore vos commentaires sur les documents de groupe dans le drive. Tout le monde doit contribuer parce que c'es un peu le bordel là dedans et Isabelle ne peut pas tout corriger ça toute seule. Il faudrait que ce soit fait pour ce soir.

Merci

**Comment by ialgrin** [comment]
Hello team !
S'il vous plait veuillez consulter les documents suivants afin de préciser des informations que d'autres membres de l'équipe auraient jugées incomplètes ou imprécises dans vos parties respectives. Je pourrai alors procéder aux vérifications ce soir.
- COMPARAISON DES VOCABULAIRES
- Note méthodologie
- Note stratégique
Vous pouvez également ajouter des notes dans le "scénario" afin qu'elles soient prises en compte pour la rédaction.
Nous mettons en commun les documents avec Ophélie du groupe ontologies demain dans l'après-midi, après avoir visionné les commentaires de Monsieur Château.
merci :)
